- name: Install mysql
  ansible.builtin.apt:
    name: mysql-server
    state: present
    update_cache: yes

- name: Start mysql
  ansible.builtin.service:
    name: mysql
    state: started
    enabled: yes

- name: Install MySQL-python
  ansible.builtin.apt:
    name: python3-pymysql
    state: present
  

- name: Create a new database
  community.mysql.mysql_db:
    name: kaizen
    state: present
    login_unix_socket: /run/mysqld/mysqld.sock

- name: Create database user with name 'aiga' and password '12345' with all database privileges
  community.mysql.mysql_user:
    name: aiga
    password: 12345
    priv: '*.*:ALL'
    state: present
    login_unix_socket: /run/mysqld/mysqld.sock